// AUTO-GENERATED by scripts/calibrate-rarity.ts. Do not edit by hand.
// Re-run `pnpm --filter web calibrate:rarity` after reseeding the card pool.
// Seed pool: 200 cards from Scarlet & Violet — Paldea Evolved (sv2).
import { Rarity } from "@prisma/client";

export type TierName = "STARTER" | "PREMIUM" | "ULTRA";
export type TierWeights = Record<Rarity, number>;

export const RARITY_WEIGHTS: Record<TierName, TierWeights> = {
  "STARTER": {
    "COMMON": 0.7112305738488708,
    "UNCOMMON": 0.21732045312048828,
    "RARE": 0.05,
    "EPIC": 0.018634189007698927,
    "LEGENDARY": 0.0028147840229420223
  },
  "PREMIUM": {
    "COMMON": 0.4611298665939231,
    "UNCOMMON": 0.2766779199563538,
    "RARE": 0.14222597331878462,
    "EPIC": 0.09908260277723693,
    "LEGENDARY": 0.02088363735370154
  },
  "ULTRA": {
    "COMMON": 0.20397849164365756,
    "UNCOMMON": 0.24477418997238906,
    "RARE": 0.21318279331492604,
    "EPIC": 0.26965592172649033,
    "LEGENDARY": 0.06840860334253697
  }
};

export const TIER_PITY: Record<TierName, "NONE" | "RARE" | "EPIC"> = {
  STARTER: "NONE",
  PREMIUM: "RARE",
  ULTRA: "EPIC",
};

export const TIER_PRICES_USD: Record<TierName, string> = {
  STARTER: "5.0000",
  PREMIUM: "20.0000",
  ULTRA: "50.0000",
};

export const TIER_CALIBRATED_EV_USD: Record<TierName, string> = {
  STARTER: "3.2345",
  PREMIUM: "15.0227",
  ULTRA: "42.4097",
};
